apiVersion: v1
kind: Service
metadata:
  name:  amvitech-service
spec:
  selector:
    name:  amvitech-frontend
  type: NodePort
  ports:
  - port:  80
    targetPort:  80
    nodePort: 30005